from __future__ import annotations

import json

import pytest

from aeep.assessment.controlled_fixture import run, verify
from aeep.assessment.verification import verify_assessment_product
from aeep.errors import ConfigurationError

pytestmark = pytest.mark.assessment_lifecycle


def test_attempt_clock_rollback_keeps_receipts_recordable():
    from datetime import timedelta

    from test_v07_execution_attempts import NOW, attempt

    from aeep.attempts import ExecutionAttemptState
    from aeep.store import ReceiptStore

    store = ReceiptStore(':memory:')
    try:
        original = store.create_execution_attempt(attempt())
        observed = NOW - timedelta(milliseconds=10)
        claimed = store.claim_execution_attempt(original.attempt_id, owner_id='fixture',
            claimed_at=observed, lease_expires_at=NOW+timedelta(minutes=1))
        assert claimed.updated_at == NOW and claimed.heartbeat_at == observed
        terminal = store.transition_execution_attempt(claimed.attempt_id,
            expected_state=claimed.state, expected_version=claimed.version,
            target_state=ExecutionAttemptState.FAILED, updated_at=observed)
        assert terminal.updated_at == NOW and terminal.heartbeat_at == observed
        assert terminal.version == claimed.version + 1
    finally:
        store.close()


def test_release_source_identity_ignores_build_metadata_only(tmp_path):
    from aeep.assessment.verification import verification_source_digest

    source = tmp_path / 'src' / 'aeep'
    source.mkdir(parents=True)
    implementation = source / 'example.py'
    implementation.write_text('original')
    (tmp_path / 'pyproject.toml').write_text('[build-system]')
    original = verification_source_digest(tmp_path)
    metadata = tmp_path / 'src' / 'aeep.egg-info'
    metadata.mkdir()
    (metadata / 'SOURCES.txt').write_text('generated by package build')
    assert verification_source_digest(tmp_path) == original
    implementation.write_text('changed')
    changed = verification_source_digest(tmp_path)
    assert changed != original
    (tmp_path / 'pyproject.toml').write_text('[build-system]\nrequires = []')
    assert verification_source_digest(tmp_path) != changed


async def test_source_bound_controlled_fixture_requires_actual_lineage(tmp_path, monkeypatch):
    record = await run(tmp_path / 'fixture')
    assert verify(tmp_path / 'fixture')['admission_id'] == record.admission_id
    monkeypatch.setattr('aeep.assessment.verification._pytest',lambda *_args:(True,''))
    checked = verify_assessment_product(controlled_fixture=tmp_path/'fixture')
    assert checked.controlled_fixture_verified and not checked.demonstrated_savings
    assert not checked.production_support_verified
    assert not checked.release_ready
    with pytest.raises(ConfigurationError,match='already contains'):
        await run(tmp_path/'fixture')
    broken = record.model_copy(update={'receipt_id':'unexecuted'})
    (tmp_path/'fixture'/'evidence.json').write_text(broken.model_dump_json())
    with pytest.raises(ConfigurationError,match='incomplete'):
        verify(tmp_path/'fixture')
    (tmp_path/'fixture'/'evidence.json').write_text(json.dumps({'success':True}))
    with pytest.raises(ValueError):
        verify(tmp_path/'fixture')
