"""AEEP: economic profiling and policy-based routing for agent actions."""

from .instrumentation import TraceIngestor, instrument_anthropic, instrument_openai
from .models import (
    ActionConstraints,
    ActionContext,
    ActionRequest,
    AgentBudget,
    BenchmarkEntry,
    BenchmarkResult,
    CapabilityDefinition,
    CounterfactualReport,
    EconomicMetrics,
    ExecutionOutcome,
    ExecutionReceipt,
    ExecutorSpec,
    Manifest,
    PersistenceConfig,
    PolicyConfig,
    ProviderDescriptor,
    Quote,
    QuoteAcceptance,
    QuoteRequest,
    RouteDecision,
    SubscriptionResource,
)
from .router import Router
from .sdk import capability, executor_from_callable
from .version import __version__

__all__ = [
    "ActionConstraints",
    "ActionContext",
    "ActionRequest",
    "AgentBudget",
    "BenchmarkEntry",
    "BenchmarkResult",
    "CapabilityDefinition",
    "CounterfactualReport",
    "EconomicMetrics",
    "ExecutionOutcome",
    "ExecutionReceipt",
    "ExecutorSpec",
    "Manifest",
    "PersistenceConfig",
    "PolicyConfig",
    "ProviderDescriptor",
    "Quote",
    "QuoteAcceptance",
    "QuoteRequest",
    "RouteDecision",
    "Router",
    "SubscriptionResource",
    "TraceIngestor",
    "__version__",
    "capability",
    "executor_from_callable",
    "instrument_anthropic",
    "instrument_openai",
]
